Forge coverage update - add test readme
allo-protocol/allo-v2 pull request #132
Opened 2023-07-27 18:34 UTC by codenamejason

2023-07-28 05:53 UTC, thelostone-mc requested changes
Could you throw in a screenshot ?  I still see the test when i. run the command :/
<img width="1319" alt="image" src="https://github.com/allo-protocol/allo-v2/assets/5358146/c0d8642c-c188-4e84-ba69-a030637e4c8d">

2023-07-28 07:30 UTC, codenamejason commented
Run:
`yarn coverage:report`

Then
`lcov --remove lcov.info -o lcov.info 'test/*' 'script/*'`

Then
` genhtml lcov.info --branch-coverage --output-dir coverage --ignore-error category`



![Screenshot 2023-07-27 at 14 21 32](https://github.com/allo-protocol/allo-v2/assets/9419140/144fd05e-8aba-415c-972d-ba49ce2aee57)

2023-07-31 07:06 UTC, thelostone-mc approved these changes

2023-07-31 07:08 UTC, thelostone-mc approved these changes

2023-07-31 07:10 UTC, merged