Code & Comment updates on core contracts
allo-protocol/allo-v2 pull request #297
Opened 2023-09-01 17:11 UTC by codenamejason

Included:
- updates if statements with reverts to one line
- adds/removes/updates some comments and NATSPEC

2023-09-02 17:40 UTC, Aryan9592 approved these changes
Nice add!

2023-09-05 06:04 UTC, thelostone-mc commented on contracts/strategies/qv-hackathon/SchemaResolver.sol
> +/// @title A base resolver contract
would recommend not changing anythig on this file as we've copied it.

2023-09-05 06:05 UTC, thelostone-mc commented on contracts/strategies/qv-base/QVBaseStrategy.sol
> +        for (uint256 i; i < _recipientIds.length;) {
this change increases gas as the .length would have to be computed at ever iteration

2023-09-05 06:09 UTC, thelostone-mc requested changes
I'd recommend we stick to wrapping if statements within a curly brackets cause it's less error prone https://softwareengineering.stackexchange.com/questions/16528/single-statement-if-block-braces-or-no

2023-09-05 13:38 UTC, thelostone-mc commented on contracts/core/Allo.sol
> +import "./interfaces/IRegistry.sol";
```suggestion
```

2023-09-05 13:40 UTC, thelostone-mc commented on contracts/strategies/BaseStrategy.sol
> +        for (uint256 i; i < _recipientIds.length;) {
uint256 length = _recipientIds.length;

2023-09-05 13:57 UTC, thelostone-mc approved these changes

2023-09-05 13:57 UTC, 0xKurt approved these changes

2023-09-05 13:59 UTC, merged