Add poc Hedgey Strategy
allo-protocol/allo-v2 pull request #319
Opened 2023-09-12 13:57 UTC by TheShobo

This adds a poc strategy (RFP Committeee) using Hedgey's linear vesting contracts for distribution.

One notable change is to `core/libraries/Transfer.sol` where we have set the transfer methods to `virtual`. This makes it far easier for integrations such as Hedgey to modify the base strategies and only have to override the necessary transfer method(s) instead of having to duplicate the `distribute` method and ensure it's kept up-to-date with the original.

2023-09-12 19:00 UTC, codenamejason commented
I approved the action but the tests are failing.

2023-09-13 13:45 UTC, TheShobo commented
> I approved the action but the tests are failing.

All resolved, I had missed running `forge fmt` to match the expected formatting.

2023-09-14 18:16 UTC, codenamejason commented
> > I approved the action but the tests are failing.
> 
> All resolved, I had missed running `forge fmt` to match the expected formatting.

Happens to me all the time 🫣

2023-09-28 15:57 UTC, thelostone-mc submitted a review, later dismissed

2023-09-29 10:32 UTC, 0xKurt commented on contracts/strategies/_poc/hedgey/HedgeyRFPCommitteeStrategy.sol
> +        adminAddress = _adminAddress;
event missing

2023-09-29 10:32 UTC, 0xKurt commented on contracts/strategies/_poc/hedgey/HedgeyRFPCommitteeStrategy.sol
> +        adminTransferOBO = _adminTransferOBO;
event missing

2023-09-29 10:32 UTC, 0xKurt commented on contracts/strategies/_poc/hedgey/HedgeyRFPCommitteeStrategy.sol
> +    function _transferAmount(address _token, address _recipient, uint256 _amount) internal override {
overwriting `_transferAmount` also affects the `withdraw` function.

2023-09-29 10:34 UTC, 0xKurt requested changes

2023-09-29 10:34 UTC, 0xKurt commented on contracts/strategies/_poc/hedgey/HedgeyRFPCommitteeStrategy.sol
> +        adminAddress = _adminAddress;
event missing

2023-09-29 10:34 UTC, 0xKurt commented on contracts/strategies/_poc/hedgey/HedgeyRFPCommitteeStrategy.sol
> +        adminTransferOBO = _adminTransferOBO;
event missing

2023-09-29 10:39 UTC, 0xKurt commented
I suggest to not merge the strategy until the current audit is finished because we are also auditing the RFP strategies this contract relies on, which may undergo changes.

2023-12-15 21:50 UTC, TheShobo commented
This branch has now been updated to work with the post-audit contracts. 
@0xKurt @codenamejason

2024-01-09 15:31 UTC, thelostone-mc approved these changes

2024-01-09 15:32 UTC, merged